/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca e-mail e senha por um token de acesso (válido por 1 hora) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description E-mail do usuário no órgão
                         */
                        email: string;
                        senha: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            /** @enum {string} */
                            tokenType: "Bearer";
                            /** @description Validade do token em segundos (3600 = 1 hora) */
                            expiresIn: number;
                        };
                    };
                };
                /** @description Erro padrão da API */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os processos do órgão (tenant) autenticado */
        get: {
            parameters: {
                query?: {
                    /** @description Página (começa em 1) */
                    page?: number;
                    /** @description Itens por página (1 a 100) */
                    limit?: number;
                    /** @description Filtra pelo status do processo */
                    status?: "em_andamento" | "concluido";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description Identificador único (UUID) */
                                id: string;
                                /** @description Número do processo */
                                numero: string;
                                titulo: string;
                                /** @enum {string} */
                                status: "em_andamento" | "concluido";
                                /** @description Data de criação em ISO 8601 (UTC) */
                                criadoEm: string;
                            }[];
                            /** @description Total de itens considerando os filtros */
                            total: number;
                            /** @description Página retornada */
                            page: number;
                        };
                    };
                };
                /** @description Erro padrão da API */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
                /** @description Erro padrão da API */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "TENANT_ID_OBRIGATORIO" | "TENANT_ID_INVALIDO" | "REQUISICAO_INVALIDA" | "CREDENCIAIS_INVALIDAS" | "TOKEN_AUSENTE" | "TOKEN_INVALIDO" | "TOKEN_EXPIRADO" | "TENANT_NAO_AUTORIZADO" | "TENANT_TOKEN_DIVERGENTE" | "RECURSO_NAO_ENCONTRADO" | "ROTA_NAO_ENCONTRADA" | "RATE_LIMIT_EXCEDIDO" | "ERRO_INTERNO";
                                /** @description Mensagem amigável em pt-BR, pronta para exibir ao usuário */
                                message: string;
                                /** @description Identificador para rastrear o erro no log */
                                requestId: string;
                                details?: {
                                    campo: string;
                                    mensagem: string;
                                }[];
                                retryAfterSeconds?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
